# Generated by Django 5.1.1 on 2024-09-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoTraducido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=30, unique=True)),
                ('contenido', models.JSONField()),
            ],
        ),
    ]
